Repository CodeLionX/actordb, pull requests merged in 2018-06, with the labels that each got.

#58 Refactor relation creation: introduce RelationDef
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/RelationDef.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/RowRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/TransientRelation.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/DactorTest.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/RowRelationTest.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/TestApplication.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/Cart.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/Customer.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/GroupManager.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/StoreSection.scala
Labels: Needs Review

#59 Proposal: New creation of relations in dactors
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/Dactor.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/DactorTest.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/TestApplication.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/Cart.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/Customer.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/GroupManager.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/StoreSection.scala
Labels: Needs Review

#66 Factory for transientrelations
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/ColumnRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/FutureRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/Relation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/RowRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/TransientRelation.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/TransientRelationTest.scala
Labels: Needs Review

#69 Fixed askDactor type annotation
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/Dactor.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/Cart.scala
Labels: Needs Review

#70 Apply a function on a column of a relation
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/FutureRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/Relation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/RowRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/TransientRelation.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/TransientRelationTest.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/TestApplication.scala
Labels: Needs Review

#71 Cart checkout
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/Cart.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/Customer.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/StoreSection.scala
Labels: Needs Review

#75 Fix Error Handling in askDactor
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/Dactor.scala
Labels: Needs Review

#73 Fix #67: Add missing scaladocs
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/Dactor.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/FutureRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/protocols/RequestResponseProtocol.scala
Labels: Merge

#78 Fix ci build
  build.sbt
  sampleapp/src/test/scala/de/up/hpi/informationsystems/sampleapp/test/dactors/SystemTest.scala
Labels: Bug (-fix), Needs Review

#77 Default values for Columns
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/ColumnDef.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/ColumnTypeDefaults.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/Record.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/ColumnDefTest.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/DactorTest.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/FutureRelationTest.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/RecordTest.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/RowRelationTest.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/TransientRelationTest.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/TestApplication.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/Cart.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/Customer.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/GroupManager.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/StoreSection.scala
  sampleapp/src/test/scala/de/up/hpi/informationsystems/sampleapp/test/dactors/SystemTest.scala
Labels: Needs Review

#86 Data Initializer for sampleapp
  .travis.yml
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/Dactor.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/csv/CSVParser.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/protocols/DefaultMessageHandling.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/protocols/DefaultMessagingProtocol.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/csv/CSVParserTest.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/DactorTest.scala
  sampleapp/src/main/resources/data/manifest/Cart-42/cart_info.csv
  sampleapp/src/main/resources/data/manifest/Cart-42/cart_purchases.csv
  sampleapp/src/main/resources/data/manifest/Customer-22/customer_info.csv
  sampleapp/src/main/resources/data/manifest/Customer-22/passwd.csv
  sampleapp/src/main/resources/data/manifest/Customer-22/store_visits.csv
  sampleapp/src/main/resources/data/manifest/GroupManager-10/discounts.csv
  sampleapp/src/main/resources/data/manifest/StoreSection-14/inventory.csv
  sampleapp/src/main/resources/data/manifest/StoreSection-14/purchase_history.csv
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/DataInitializer.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/Main.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/Cart.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/Customer.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/GroupManager.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/StoreSection.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/SystemInitializer.scala
  sampleapp/src/test/scala/de/up/hpi/informationsystems/sampleapp/test/dactors/SystemTest.scala
Labels: Needs Review

#87 Refactored adbms packages
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/Dactor.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/Exceptions.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/Util.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/csv/CSVParser.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/ColumnRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/RelationDef.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/protocols/DefaultMessageHandling.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/protocols/DefaultMessagingProtocol.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/protocols/RequestResponseProtocol.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/record/ColumnCellMapping.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/record/Record.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/relation/FutureRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/relation/MutableRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/relation/Relation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/relation/RowRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/relation/TransientRelation.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/DactorTest.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/csv/CSVParserTest.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/record/RecordTest.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/relation/FutureRelationTest.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/relation/RowRelationTest.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/relation/TransientRelationTest.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/Exceptions.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/TestApplication.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/Cart.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/Customer.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/GroupManager.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/StoreSection.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/SystemInitializer.scala
  sampleapp/src/test/scala/de/up/hpi/informationsystems/sampleapp/test/HelloWorldActorTest.scala
  sampleapp/src/test/scala/de/up/hpi/informationsystems/sampleapp/test/dactors/StoreSectionTest.scala
  sampleapp/src/test/scala/de/up/hpi/informationsystems/sampleapp/test/dactors/SystemTest.scala
Labels: Needs Review

#89 Change RequestResponseProtocol.Success to wrap around Relation instead of Seq[Record]
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/Dactor.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/protocols/RequestResponseProtocol.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/relation/MutableRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/relation/Relation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/relation/RowRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/relation/TransientRelation.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/relation/TransientRelationTest.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/Cart.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/Customer.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/GroupManager.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/StoreSection.scala
  sampleapp/src/test/scala/de/up/hpi/informationsystems/sampleapp/test/dactors/StoreSectionTest.scala
  sampleapp/src/test/scala/de/up/hpi/informationsystems/sampleapp/test/dactors/SystemTest.scala
Labels: Needs Review

#91 Add Memory Overhead benchmark notes for small/medium/big init data
  doc/data_notes.md
  doc/notes
Labels: Needs Review

#88 Data Generation Script for Memory / Load tests
  scripts/generateData.sh
Labels: Needs Review
