Repository CodeLionX/actordb, pull requests merged in 2018-05, with the labels that each got.

#8 API for creating relations
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/ColumnDef.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/ColumnRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/ColumnStore.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/Record.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/Relation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/RowRelation.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/HelloWorld.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/TestApplication.scala
Labels: Needs Review

#12 Fix #11 return None instead of Some(null) from Record.get
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/Record.scala
Labels: Merge

#9 Rename `ColumnDef`s
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/ColumnDef.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/ColumnRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/ColumnStore.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/Record.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/Relation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/RowRelation.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/TestApplication.scala
Labels: Needs Review

#14 Fix Optional instantiation formerly using Some()
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/ColumnStore.scala
Labels: Merge

#15 Setup CI (travis-ci)
  .travis.yml
  README.md
Labels: Needs Review

#13 Adding projection (SELECT) to Record and Relations
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/ColumnRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/Exceptions.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/Record.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/Relation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/RowRelation.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/RecordTest.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/TestApplication.scala
Labels: Needs Review

#27 skip PR builds for doc/* branches
  .travis.yml
Labels: Needs Review

#25 Refactor Relation API to favor inheritance
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/ColumnRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/Relation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/RowRelation.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/RecordTest.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/TestApplication.scala
Labels: Needs Review

#29 Use Set instead of Seq for columns in Records and Relations
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/ColumnDef.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/ColumnRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/Record.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/Relation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/RowRelation.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/RecordTest.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/TestApplication.scala
Labels: Merge

#32 Add ColumnDefTest
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/ColumnDefTest.scala
Labels: Merge, Needs Review

#26 Feature/dactor
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/Dactor.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/Relation.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/TestApplication.scala
Labels: Needs Review

#38 StoreSection actor bootstrap
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/TestApplication.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/StoreSection.scala
Labels: Merge

#31 Add RowRelationTest
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/ColumnRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/Relation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/RowRelation.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/RowRelationTest.scala
Labels: Merge

#43 Add TransientRelation and fluent interface for Relations
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/Util.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/ColumnRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/Relation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/RowRelation.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/TransientRelation.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/RowRelationTest.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/TransientRelationTest.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/TestApplication.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/StoreSection.scala
Labels: Needs Review

#44 Run TestApplication during CI build
  .travis.yml
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/TestApplication.scala
Labels: Needs Review

#47 Sample Application Actors
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/Dactor.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/TestApplication.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/Cart.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/Customer.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/GroupManager.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/StoreSection.scala
Labels: Needs Review

#55 Add .dactorSelection to Dactor companion object
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/Dactor.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/DactorTest.scala
Labels: Merge

#57 Allow generic inserts for all `Dactor`s
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/Dactor.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/definition/Record.scala
  adbms/src/main/scala/de/up/hpi/informationsystems/adbms/protocols/DefaultMessagingProtocol.scala
  adbms/src/test/scala/de/up/hpi/informationsystems/adbms/definition/DactorTest.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/TestApplication.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/Cart.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/Customer.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/GroupManager.scala
  sampleapp/src/main/scala/de/up/hpi/informationsystems/sampleapp/dactors/StoreSection.scala
Labels: Needs Review
